name: Main CI metrics-load-balancer 
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Lint
        run: mise run lint

      - name: Build
        run: mise run build
        
      - name: Run Tests
        run: mise run test
